from Lista01.Q06ListadeContasBancarias import *

print("Criando a lista de contas")
listadeContas = ListadeContasBancarias()
print("")
print("Lista está vazia?")
print(listadeContas.esta_vazia())
print("")
print("Criando Conta Corrente")
contaBancaria5234 = ContaBancaria(5234, 100, 100)

print("Criando Conta Poupança")
contaPoupanca2346 = ContaPoupanca(2346, 150, 0)

print("Criando Conta Fidelidade")
contaFidelidade3247 = ContaFidelidade(3247, 200, 200, 0)

print("Criando Conta Fidelidade")
contaFidelidade3657 = ContaFidelidade(3657, 200, 250, 0)
print("")
print("Inserindo na lista")
listadeContas.inserirOrdenado(contaBancaria5234)
listadeContas.inserirOrdenado(contaPoupanca2346)
listadeContas.inserirOrdenado(contaFidelidade3247)
listadeContas.inserirOrdenado(contaFidelidade3657)
print("")
print("Impressão direta")
listadeContas.printLista()
print("")
print("Impressão recursiva")
listadeContas.printListaRecursivo()
print("")
print("")
print("Impressão Reversa")
listadeContas.printListaReversa()
print("")
print("")
print("Lista está vazia?")
print(listadeContas.esta_vazia())
print("")

print("Buscando uma conta existente")
print(listadeContas.buscaElemento(5234)._conta._numero)
print("")

print("Buscando uma conta inexistente")
contaBuscada = listadeContas.buscaElemento(3421)
if contaBuscada != None:
    print(contaBuscada._conta._numero)
else:
    print("Conta não encontrada")
print("")

print("Removendo um determinado elemento (5234) da lista")
listadeContas.removeItem(5234)
listadeContas.printLista()
print("")

print("Criando Conta Corrente 6765")
contaBancaria6765 = ContaBancaria(6765, 100, 80)
listadeContas.inserirOrdenado(contaBancaria6765)
listadeContas.printLista()
print("")

print("Removendo itens (3247) recursivamente")
listadeContas.removeItemRecursivamente(3247)
listadeContas.printLista()
print("")

print("Listando as contas e saldos")
listadeContas.printContasLista()
print("")
print("Efetuando crédito de 80,00 na conta 6765")
listadeContas.efetuar_credito(6765, 80)
print("Saldo da Conta 6765: ")
print(listadeContas.get_saldo(6765))
print("")
print("Listando as contas e saldos")
listadeContas.printContasLista()
print("")
print("Listando mais flexível com detalhes:")
listadeContas.printDetalhesLista()
print("")
print("Fazendo uns creditos em conta fidelidade 3657:")
print("120 na conta 3657")
print("Novos saldos:")
listadeContas.efetuar_credito(3657, 120)
listadeContas.printDetalhesLista()
print("Consultando o bônus da conta 3657:")
print(listadeContas.get_bonus(3657))
print("")
print("Consultando o bônus de conta não fidelidade:")
print(listadeContas.get_bonus(6765))
print("Listando os detalhes:")
listadeContas.printDetalhesLista()
print("Fazendo um débito maior que o saldo+limite:")
print("Debitando 200 na conta 2346:")
if listadeContas.efetuar_debito(2346, 200):
    print("Sucesso!")
    listadeContas.printDetalhesLista()
else:
    print("Falha!")
print("")
print("Fazendo uma transferência que dá certo")
listadeContas.printDetalhesLista()
print("Operação: Transferir 100 da conta 3657 para a conta 2346")
if listadeContas.efetuar_transferencia(3657, 2346, 100):
    print("Sucesso!")
else:
    print("Falha")
listadeContas.printDetalhesLista()

print("")
print("Fazendo uma transferência que falha por falta de Saldo")
listadeContas.printDetalhesLista()
print("Operação: Transferir 400 da conta 6765 para a conta 3657")
if listadeContas.efetuar_transferencia(6765, 3657, 400):
    print("Sucesso!")
else:
    print("Falha")
listadeContas.printDetalhesLista()

print("")
print("Render juros em poupança 5% na conta 2346")
listadeContas.render_juros(2346, 0.05)
listadeContas.printDetalhesLista()

print("")
print("Render bônus conta 3657")
listadeContas.render_bonus(3657)
listadeContas.printDetalhesLista()

print("")
print("Liberando a Lista")
listadeContas.libera()
