from set import *

print("Criando o conjunto")
mySet1 = Set()
print("Seu universo será tudo o que for printável; pode ser outro se quizer")
mySet1.setUniverso(printable)
print("Printando o Universo")
mySet1.printUniverso()
print("Acrescentando alguns elementos: jose florencio")
mySet1.addElementos('jose florencio')
mySet1.printConjunto()
mySet2 = Set()
mySet2.setUniverso(mySet1.getUniverso())
mySet2.addElementos('de queiroz neto')
print("=============================================")
print("União de conjuntos")
print("--------------------")
print("Conjunto 1")
mySet1.printConjunto()
print("Conjunto 2")
mySet2.printConjunto()
print("Resultado")
mySet1.uniao(mySet2)
mySet1.printConjunto()
print("=============================================")
print("Remoção de elementos")
print("--------------------")
print("Conjunto 1")
mySet1.printConjunto()
print("Removendo: queiroz")
mySet1.delElementos('queiroz')
print("Resultado")
mySet1.printConjunto()
print("=============================================")
print("Interseção de conjuntos")
print("-----------------------")
print("Conjunto 1")
mySet1.printConjunto()
print("Conjunto 2")
mySet2.printConjunto()
mySet1.intersecao(mySet2)
print("Resultado")
mySet1.printConjunto()
print("=============================================")
print("Diferença de conjuntos")
print("-----------------------")
mySet1.addElementos('florencio')
print("Conjunto 1")
mySet1.printConjunto()
print("Conjunto 2")
mySet2.printConjunto()
print("Conjunto 1 - Conjunto 2 =")
mySet1.diferenca(mySet2)
mySet1.printConjunto()
print("=============================================")
print("Verificar se é subconjunto")
print("-----------------------")
mySet1.addElementos('florencio')
print("Conjunto 1")
mySet1.printConjunto()
print("Conjunto 2")
mySet2.printConjunto()
print("Conjunto 2 é subconjunto de Conjunto 1?")
print(mySet1.subconjunto(mySet2))
mySet2.delElementos('florencio de queiroz neto')
mySet2.addElementos('rencio')
print("Conjunto 2")
mySet2.printConjunto()
print("Conjunto 2 é subconjunto de Conjunto 1?")
print(mySet1.subconjunto(mySet2))
print("=============================================")
print("Verificar igualdade de conjuntos")
print("-----------------------")
mySet1.addElementos('florencio')
print("Conjunto 1")
mySet1.printConjunto()
print("Conjunto 2")
mySet2.printConjunto()
print("Conjunto 1 é igual ao Conjunto 2?")
print(mySet1.igual(mySet2))
mySet2.setElementos('florencio')
print("Conjunto 2")
mySet2.printConjunto()
print("Conjunto 1 é igual ao Conjunto 2?")
print(mySet1.igual(mySet2))
print("=============================================")
print("Gerar o complemento de um conjunto")
print("-----------------------")
mySet1.setUniverso('abcdefgh')
mySet1.printUniverso()
mySet1.setElementos('qazwsxedc')
print("Conjunto 1")
mySet1.printConjunto()
print("Print complemento de Conjunto 1")
print(mySet1.complemento())
print("=============================================")
print("Verificar se um elemento pertence a um conjunto")
print("-----------------------")
mySet1.setUniverso('qazwsxedc')
mySet1.setElementos('qazwsxedc')
print("Conjunto 1")
mySet1.printConjunto()
print("Elemento 'a' faz parte de Conjunto 1?")
print(mySet1.pertence('a'))
print("Elemento 'b' faz parte de Conjunto 1?")
print(mySet1.pertence('b'))
print("=============================================")
print("Verificar o número de elementos de um conjunto")
print("-----------------------")
mySet1.setUniverso('qazwsxedc')
mySet1.setElementos('qsxedc')
print("Conjunto 1")
mySet1.printConjunto()
print("Número de elementos do conjunto:")
print(mySet1.tamanho())
print("=============================================")
print("Liberando a memória")
mySet1.libera()
mySet2.libera()
del mySet1
del mySet2
